# Lists [/list/{category}]

## GET
  + Parameters
    + category (string) - The category of the items as a string
  + Response 200 (application/json)
  + Body
    {
     "category":"movies",
     "items":[
        {
           "id":"1",
           "properties":[
              {
                 "name":"Human Centipede",
                 "year":2009
              }
           ]
        },
        {
           "id":"2",
           "properties":[
              {
                 "name":"Human Centipede 2",
                 "year":2011
              }
           ]
        }
     ]
    }

## POST
  + Request (application/json)
    {
       "properties":[
          {
             "name":"Human Centipede",
             "year":2009
          }
       ]
    }
  + Response 204 (application/json)
